# NOTE(mroberts): https://github.com/travis-ci/travis-ci/issues/4704
filter_secrets: false
language: node_js
node_js:
  - 7

# https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required

script:
  - yarn build
  - git status

notifications:
  slack:
    secure: hwoFCLArGwb10mNAEd86mrrlGU4xPYIdZoAX1BncfMF97e5WdCmERAqci9JP6svYcjWZZhdw0RW5My/9qoEGfp2Y307plS1W7QtN3c/iBDHYC7QqQg7cvLgrqQ2mAu091kEqqveJM3SZrAGFXKjsRxbcDJoFoSmJSsA9GLKTuoAbDf61ZEODzjuv3jHHL3vxsTXLXzIsGOYxU68v0yC55OKRiXk6ctD5Mlhw0EGJLMUDR597uTheqSC7PctbfQf0c9U9wfkKryJl14T2IDpYnv7mrDzqRU0zHttQrcDDcGEnqiRzyxtqeT0HA2ZBL8RbspWOqfHN/cxwOz5ALsaMzi9Vo8RiMnMc4YFyJ2K11PxQEPB2+E9TIf04ejUjs5uqDfnx4yTxj7uw4Ve6IyyJFJDfYxO0b8+YrRF++BleXU8rVIRshZnWhaBVQochHsxz/ETAUI2nbugzv/8stA9+ZNnO2ByLFG8NwF2nwSPVmaHn6qQ36cLfIQbgWMUS2+qzInkZkqoDs6BKCR2o/iN9d9uhmxT6b7RX0iPK4NofRnHznzZzHBmdm1hvg0oyZahSG7pi7e2tLxRzbI2//2Z8FVEos8PL1GPHrrVCwAwWftmEg+KBW+VBcFivngLG+TWwLUgObzV5hrG99t4EZQXHqk1nsNTROMfAZhfjsul4C0w=
